#! /bin/bash

DIR=$( cd "$( dirname "$0" )" &&  pwd )

sudo apt-get install ghostscript libgs-dev gs-esp liblcms2-2 liblcms2-dev librsvg2-2 librsvg2-dev libxml2-dev libfreetype6-dev

mkdir -p ~/im-build
cd ~/im-build

curl http://www.imagemagick.org/download/ImageMagick-6.9.2-6.tar.gz | tar xzv

cd ~/im-build/ImageMagick-6.9.2-6

./configure --with-rsvg=yes --enable-shared=no --prefix=$HOME/im-build-out
make 
sudo make install
cd ~/im-build-out

# need configure.xml on heroku
sudo cp share/doc/ImageMagick-6/www/source/configure.xml etc/ImageMagick-6/

# patched delegates.xml
#sudo cp $DIR/delegates.xml etc/ImageMagick-6/

tar -czvf $DIR/imagemagick.6.9.2.tgz bin etc lib


